### ISSUE TITLE
When using append mode, if making a new highlight in an article already synced to Obsidian, **all** highlights will be synced, durplicating previously highlights that were previously synced

### ISSUE THREAD

**Issue by ghost** [kaiiiz/obsidian-raindrop-highlights-plugin#47] opened 2023-05-23 21:14 UTC
When using append mode, say I do the following:
- Make some highlights in an article in raindop
- Sync those highlights to Obsidian using the raindrop-highlights-plugin
- At a later time, make new additional highlights in the same article as before in raindrop
- Sync all highlights from raindrop to obsidian again
- Highlights that were previously synced into my Obsidian note for that article will be repeated, as well as including the new highlights

I do not belive this is intended behaviour. When using append mode, I would expect that only new highlights will be synced to the note in my Obsidian vault that corrosponds with that article.

Please could this be looked into? I have tried many times to reinstall the plugin, and make sure that the settings I am working with are okay. But despite this, whenever I try append mode, it causes previously synced highlights to be duplicated when syncing additional highlights in an article. It is stopping me from using what otherwise is a fantastic plugin!!

Really appreciate your help with this one. Thanks for all the work done on this plugin so far. I hope the explanation of my issue was understandable.

**Comment by MidnightGond** [comment] 2023-05-26 11:33
Is this plugin being actively maintained?

**Comment by kaiiiz** [comment] 2023-06-17 06:16
I've checked this issue and can reproduce this bug.

The root cause of this bug is not the `raindrop_last_update` issue since it stores the ISO 8601 format (UTC), so the timezone does not affect the date comparison result.

After looking into the details, I found that the `lastUpdate` field in the highlight of the Raindrop API response doesn't provide the correct result. The `lastUpdate` of the old highlights will be overridden if the new highlights are added to the article.

I've submitted the bug report to Raindrop. Please keep track of the status in https://raindropio.canny.io/bugs/p/wrong-lastupdate-value-in-the-highlights-field-of-the-httpsapiraindropiorestv1ra.

**Comment by kaiiiz** [comment] 2023-07-19 16:42
The bug report remains unanswered, with no response yet from Raindrop's official team. Therefore, I came up with a straightforward idea to fix this issue.

Instead of using the `lastUpdate` information, we can store the hash signature for each highlighted entry in either the YAML front matter or the plugin's `data.json`, which can be derived from the combination of `highlight id`, `highlight content` and `annotation`. When the plugin updates a bookmark, it will compare the derived highlight signature from the API response with the stored signatures to determine if a new highlight needs to be appended to the Obsidian note. This approach should resolve the duplicate issue.

However, some migration works must be done and carefully designed to minimize its impact on users. Here's what I've come up with so far:

1. Personally, I prefer storing the highlight signatures in the YAML front matter as it's more portable than storing them in the plugin's `data.json`. However, this may make the front matter become messy. Maybe a more compact encoding strategy can eliminate this issue. (e.g. `base64(hash1, hash2)` v.s. `[hash1, hash2]`)
2. I'm considering how to migrate to this new implementation more smoothly. One approach could be to first generate signatures for all pulled Raindrop notes and add them to the YAML front matter. However, this might result in losing some updates from the last sync, as we won't be able to distinguish whether a highlight has been updated or not.

Any suggestions/discussions are welcome.

**Comment by omega3** [comment] 2023-08-10 11:37
For me append mode doesn't work at all. - I am on the latest appimage. Every time I sync a new note is created.

**Comment by gregheth** [comment] 2023-09-21 07:21
Thanks kaiiiz. When you flagged "help wanted" what did you have in mind?  I know coding but I don't know Obsidian plugin coding.  But I am willing to learn

**Comment by kaiiiz** [comment] 2023-10-03 17:03
Fixed in v0.0.19.

**Closed by kaiiiz** 2023-10-03 17:03 UTC
Labels: bug
