### ISSUE TITLE
"Can't find variable: Buffer"

### ISSUE THREAD

**Issue by robertandrews** [kaiiiz/obsidian-raindrop-highlights-plugin#3] opened 2022-08-08 18:08 UTC
On iPad, a previously-authenticated install is reporting "Can't find variable: Buffer".

My initial setup a few days ago was a little problematic. Initial iPad plugin install (0.0.9) (via BRAT) seemed to work. Then it simply wouldn't pull any bookmarks. I moved to iMac to use Developer Tools to check for messages. It was warning about a problem with the token, so I re-pasted it in, and then pulling bookmarks on iMac worked (and continues to work).

However, on iPad, with the same Obsidian account etc, synced through iCloud, it throws this error and will not pull new bookmarks. I can only sync successfully on Mac.

Anything to do with https://github.com/kaiiiz/obsidian-raindrop-highlights-plugin/blob/c1bbec024b9d06338153f03cd91306eb657c509c/yarn.lock#L217 ?

**Comment by kaiiiz** [comment] 2022-08-10 13:35
This is caused by [gray-matter](https://github.com/jonschlinkert/gray-matter/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+Buffer), as it seems to only work on the node.js back-end properly. I've replaced the implementation of front matter update logic from gray-matter with built-in `parseYaml` and `stringifyYaml`. This is fixed in the 0.0.10 release, please check out the latest version.

**Comment by robertandrews** [comment] 2022-08-10 15:36
Seems to work! I deleted 0.0.9, which had been a release-specific install, installed 0.0.10 fresh, set it up and did a sync pull. It added okay on iPadOS.

**Closed** 2022-08-10 16:06 UTC
Labels: bug

**Comment by kaiiiz** [comment] 2022-08-11 03:25
v0.0.10 replaced the frontmatter update logic from gray-matter to built-in `parseYaml` and `stringifyYaml`.

However, I noticed that `app.metadataCache.getFileCache` has an unexpected behavior after appending the new content to the file. The frontmatter object inside `metadataCache` is `null` instead of the latest object. This caused frontmatter duplication bug while updating the post.

I've fixed this issue in v0.0.11. It should work properly now.
